---

- name: Install New Relic PHP dependencies
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - apt-utils
    state: present
  retries: 2
  register: sansible_newrelic_agent_php_deps_result
  until: sansible_newrelic_agent_php_deps_result is succeeded

- name: Download New Relic PHP PGP key (works with Bionic behind a proxy)
  become: yes
  get_url:
    dest: /usr/local/src/newrelic_php.asc
    mode: 0644
    url: "https://{{ sansible_newrelic_agent_php_apt_repo_keyserver }}/pks/lookup?op=get&search=0x{{ sansible_newrelic_agent_php_apt_key_id }}"
  retries: 2
  register: sansible_newrelic_agent_php_apt_key_result
  until: sansible_newrelic_agent_php_apt_key_result is succeeded

- name: Ensures New Relic PHP PGP key is known
  become: yes
  apt_key:
    file: /usr/local/src/newrelic_php.asc
    id: "{{ sansible_newrelic_agent_php_apt_key_id }}"
    state: present

- name: Add New Relic PHP Repo
  become: yes
  apt_repository:
    repo: "{{ sansible_newrelic_agent_php_apt_repo }}"
    state: present
    update_cache: yes

- name: Install New Relic PHP agent
  become: yes
  apt:
    pkg:
      - "newrelic-php5-common={{ sansible_newrelic_agent_php_version }}"
      - "newrelic-daemon={{ sansible_newrelic_agent_php_version }}"
      - "newrelic-php5={{ sansible_newrelic_agent_php_version }}"
    state: present
  retries: 2
  register: sansible_newrelic_agent_php_install_result
  until: sansible_newrelic_agent_php_install_result is succeeded

- name: Disable New Relic PHP agent until enabled
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ sansible_newrelic_agent_php_ini_paths_links }}"
  when: sansible_newrelic_agent_php_install_result.changed
  tags:
    - skip_ansible_lint

- name: Ensure New Relic PHP Daemon service is disabled
  become: yes
  service:
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
    enabled: no
    name: newrelic-daemon
